const TRANSACTION_TABS=['manual','inbound','outbound'];
function inboundPanelHtml(){return `<div class="card compact inbound-step-card"><div class="inbound-step-title"><span>1</span><div><h3>입고자료 선택</h3><p class="hint">상세구분에 따라 사무실 입고 또는 회수로 변환합니다.</p></div></div><div class="toolbar"><button type="button" class="btn primary" onclick="byId('inboundFile').click()">입고자료 엑셀 선택</button><input id="inboundFile" type="file" accept=".xlsx,.xls" class="hidden" onchange="handleInboundFile(event)"><span id="inboundFileName" class="hint">선택된 파일 없음</span></div></div>
<div id="inboundSummaryCard" class="card compact inbound-step-card hidden"><div class="inbound-step-title"><span>2</span><div><h3>자료 확인</h3></div></div><div class="inbound-summary-grid"><div><small>전체 행</small><strong id="inboundRowCount">0</strong></div><div><small>배송수량 합계</small><strong id="inboundQtyTotal">0</strong></div><div><small>제품 조합</small><strong id="inboundProductCount">0</strong></div><div class="ok"><small>매칭 완료</small><strong id="inboundMatchedCount">0</strong></div><div class="warn"><small>매칭 필요</small><strong id="inboundUnmatchedCount">0</strong></div><div><small>이미 등록</small><strong id="inboundDuplicateCount">0</strong></div><div class="ok"><small>등록 가능 입고</small><strong id="inboundIncomingCount">0</strong></div><div class="warn"><small>등록 가능 회수</small><strong id="inboundRecoveryCount">0</strong></div></div></div>
<div id="inboundMappingCard" class="card inbound-step-card hidden"><div class="inbound-step-title"><span>3</span><div><h3>제품 변환·매칭</h3></div></div><div class="toolbar inbound-filter-toolbar"><input id="inboundMappingSearch" placeholder="외부 제품코드 또는 제품명 검색" oninput="renderInboundMappings()"><select id="inboundMappingFilter" onchange="renderInboundMappings()"><option value="all">전체</option><option value="unmatched">매칭 필요만</option><option value="matched">매칭 완료만</option></select><button class="btn" onclick="saveInboundMappings()">매칭 저장</button></div><datalist id="inboundProductOptions"></datalist><div class="table-wrap inbound-mapping-table-wrap"><table><thead><tr><th>상태</th><th>외부 제품코드</th><th>원본 제품명</th><th>행 수</th><th>수량</th><th>품목 Master 매칭</th></tr></thead><tbody id="inboundMappingTable"></tbody></table></div></div>
<div id="inboundPreviewCard" class="card inbound-step-card hidden"><div class="inbound-step-title"><span>4</span><div><h3>사무실 입고·회수 등록</h3><p class="hint">상세구분에 반품 또는 회수가 포함되면 회수, 그 외에는 입고로 등록합니다.</p></div></div><div class="toolbar"><button id="inboundCommitBtn" class="btn primary" onclick="commitInboundTransactions()">등록 가능한 자료 반영</button><span id="inboundCommitHint" class="hint"></span></div><div id="inboundCommitResult" class="mt"></div><div class="table-wrap inbound-preview-table-wrap mt"><table><thead><tr><th>상태</th><th>입고일</th><th>전표번호</th><th>상세구분</th><th>등록구분</th><th>제품코드</th><th>품목 Master</th><th>수량</th><th>LOT</th><th>SERIAL</th></tr></thead><tbody id="inboundPreviewTable"></tbody></table></div></div>`;}
function outboundPanelHtml(){return `<div class="card compact inbound-step-card"><div class="inbound-step-title"><span>1</span><div><h3>출고자료 선택</h3><p class="hint">G열 문서구분이 매입가납인 행을 선납으로 변환하고 V열 납품처명을 거래처와 연결합니다.</p></div></div><div class="toolbar"><button type="button" class="btn primary" onclick="byId('outboundFile').click()">출고자료 엑셀 선택</button><input id="outboundFile" type="file" accept=".xlsx,.xls" class="hidden" onchange="handleOutboundFile(event)"><span id="outboundFileName" class="hint">선택된 파일 없음</span></div></div>
<div id="outboundSummaryCard" class="card compact inbound-step-card hidden"><div class="inbound-step-title"><span>2</span><div><h3>자료 확인</h3></div></div><div class="inbound-summary-grid"><div><small>전체 행</small><strong id="outboundRowCount">0</strong></div><div><small>수량 합계</small><strong id="outboundQtyTotal">0</strong></div><div><small>매칭 조합</small><strong id="outboundGroupCount">0</strong></div><div class="ok"><small>등록 가능</small><strong id="outboundReadyCount">0</strong></div><div class="warn"><small>매칭 필요</small><strong id="outboundUnmatchedCount">0</strong></div><div class="warn"><small>문서구분 제외</small><strong id="outboundUnsupportedCount">0</strong></div><div><small>이미 등록</small><strong id="outboundDuplicateCount">0</strong></div></div></div>
<div id="outboundMappingCard" class="card inbound-step-card hidden"><div class="inbound-step-title"><span>3</span><div><h3>거래처·제품 매칭</h3><p class="hint">납품처명은 거래처 Master, 제품은 품목 Master와 연결합니다.</p></div></div><div class="toolbar inbound-filter-toolbar"><input id="outboundMappingSearch" placeholder="납품처명·제품코드·제품명 검색" oninput="renderOutboundMappings()"><select id="outboundMappingFilter" onchange="renderOutboundMappings()"><option value="all">전체</option><option value="unmatched">매칭 필요만</option><option value="matched">매칭 완료만</option></select><button class="btn" onclick="saveOutboundMappings()">매칭 저장</button></div><datalist id="outboundProductOptions"></datalist><datalist id="outboundCustomerOptions"></datalist><div class="table-wrap outbound-mapping-table-wrap"><table><thead><tr><th>상태</th><th>납품처명</th><th>외부 제품코드</th><th>원본 제품명</th><th>행 수</th><th>수량</th><th>거래처 매칭</th><th>품목 매칭</th></tr></thead><tbody id="outboundMappingTable"></tbody></table></div></div>
<div id="outboundPreviewCard" class="card inbound-step-card hidden"><div class="inbound-step-title"><span>4</span><div><h3>선납 거래 등록</h3><p class="hint">비고에는 전표번호와 LOT만 저장합니다.</p></div></div><div class="toolbar"><button id="outboundCommitBtn" class="btn primary" onclick="commitOutboundTransactions()">등록 가능한 자료 반영</button><span id="outboundCommitHint" class="hint"></span></div><div id="outboundCommitResult" class="mt"></div><div class="table-wrap outbound-preview-table-wrap mt"><table><thead><tr><th>상태</th><th>출고일</th><th>전표번호</th><th>문서구분</th><th>등록구분</th><th>납품처명</th><th>거래처 Master</th><th>제품코드</th><th>품목 Master</th><th>수량</th><th>LOT</th></tr></thead><tbody id="outboundPreviewTable"></tbody></table></div></div>`;}
function buildTransactionTabs(){
  const section=document.querySelector('main.main > section');if(!section||section.dataset.tabsReady)return;
  section.dataset.tabsReady='1';const original=[...section.childNodes];section.innerHTML='';
  const tabs=document.createElement('div');tabs.className='transaction-tabs';tabs.setAttribute('role','tablist');tabs.innerHTML='<button class="transaction-tab" data-transaction-tab="manual" onclick="setTransactionTab(\'manual\')">직접 등록·거래내역</button><button class="transaction-tab" data-transaction-tab="inbound" onclick="setTransactionTab(\'inbound\')">입고·회수 업로드</button><button class="transaction-tab" data-transaction-tab="outbound" onclick="setTransactionTab(\'outbound\')">출고 업로드</button>';section.appendChild(tabs);
  const manual=document.createElement('div');manual.dataset.transactionPanel='manual';manual.className='transaction-tab-panel';original.forEach(node=>manual.appendChild(node));section.appendChild(manual);
  const inbound=document.createElement('div');inbound.dataset.transactionPanel='inbound';inbound.className='transaction-tab-panel hidden';inbound.innerHTML=inboundPanelHtml();section.appendChild(inbound);
  const outbound=document.createElement('div');outbound.dataset.transactionPanel='outbound';outbound.className='transaction-tab-panel hidden';outbound.innerHTML=outboundPanelHtml();section.appendChild(outbound);
}
function setTransactionTab(tab,persist=true){
  const selected=TRANSACTION_TABS.includes(tab)?tab:'manual';
  document.querySelectorAll('[data-transaction-tab]').forEach(button=>{
    const active=button.dataset.transactionTab===selected;
    button.classList.toggle('active',active);
    button.setAttribute('aria-selected',String(active));
  });
  document.querySelectorAll('[data-transaction-panel]').forEach(panel=>panel.classList.toggle('hidden',panel.dataset.transactionPanel!==selected));
  if(persist)sessionStorage.setItem('DK_TRANSACTION_TAB',selected);
  if(selected==='inbound'&&typeof populateInboundOptions==='function')populateInboundOptions();
  if(selected==='outbound'&&typeof populateOutboundOptions==='function')populateOutboundOptions();
}
document.addEventListener('DOMContentLoaded',()=>{
  buildTransactionTabs();
  const requested=new URLSearchParams(location.search).get('tab');
  setTransactionTab(requested||sessionStorage.getItem('DK_TRANSACTION_TAB')||'manual',false);
});
